import Head from "next/head";
import CityTable from "../components/cityTable";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Programming Challenge</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <CityTable />
      </main>
    </div>
  );
}
